DROP TABLE IF EXISTS `DB_CENTER`.`T_USER_INFO`;
CREATE TABLE `DB_CENTER`.`T_USER_INFO` (
  F_USER_ID     BIGINT      NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  F_CHANNEL_ID  INT         NOT NULL                COMMENT '渠道ID',
  F_USER_TYPE   TINYINT     NOT NULL                COMMENT '用户类型 0: 游客, 1: 正式用户',
  F_USER_NAME   VARCHAR(32) NOT NULL                COMMENT '用户名, 手机号或邮箱',
  F_PASSWORD    CHAR(32)    NOT NULL                COMMENT '密码',
  F_NICKNAME    VARCHAR(16) NOT NULL DEFAULT ''     COMMENT '昵称',
  F_REGIST_TIME BIGINT      NOT NULL                COMMENT '注册时间',
  F_LAST_UPDATE BIGINT      NOT NULL                COMMENT '最后更新时间',
  F_STATE       TINYINT     NOT NULL DEFAULT 1      COMMENT '用户状态, 1: 激活, 0: 禁用',
  
  PRIMARY KEY(F_USER_ID),
  UNIQUE KEY(F_USER_NAME),
  INDEX(F_USER_TYPE),
  INDEX(F_REGIST_TIME),
  INDEX(F_STATE)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '用户注册信息表';
ALTER TABLE `DB_CENTER`.`T_USER_INFO` AUTO_INCREMENT = 100000;