channel_id: 1
node_code: ae906ff9-552b-4f63-b807-95a1195deddf
manager_host: ":9090"
front:
    tcp_endpoint: ":8081"
    ws_endpoint: ":8080"
    max_conn: 1000
    timeout(s): 300
backend:
    tcp_endpoint: ":6688"
redis:
    addr: "192.168.0.104:6379"
    username: ""
    password: ""
